# Generated by Django 5.0.3 on 2024-03-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("carga_horaria", models.CharField(max_length=255)),
                ("codigo", models.CharField(editable=False, max_length=155)),
            ],
        ),
    ]
